### ISSUE TITLE
Add support for 'temporary queues'

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/messaging-replication#14]
Although it must be possible already, explicit support shall be added to support 'temporary queues'.

With TQ's it is possible to interact with eXist-db in a request-response style, using JMS.this can be a good alternative over HTTP.

note: eXist-db will not initiate a temp. queue connection, because this will potentially block the database by over-consuming database brokers

**Comment by adamretter** [comment]
Dannes,

We are using temporary queues in another project for doing Request/Response over JMS (with ActiveMQ). I just wanted to mention that they should not be considered performant, there is an overhead with creating a temporary queue for every request/response operation. Also you need to remember to set the correct security properties on the temporary queues, and also to tear them down when you are finished with them.

**Comment by dizzzz** [comment]
I know that TQs are not performant due to the overhead. I guess that connection pooling/buffering (object reuse) does not help here? I spent quite some time introducing the buffering in the extension.

About the security/cleanup issues you mention: does this apply to clients that connect to the system only, or will there some challenges involved for the eXist-db extension?

**Comment by adamretter** [comment]
Well for any JMS queue, you need to have a security policy, otherwise anyone could inject any malicious message into your queue, or read off messages from the queue and prevent others from receiving them. The same is true of temporary queues, however as you created them dynamically you may also have to apply the security policy to them dynamically (depending on how you have Active MQ configured).

Regards the tear-down of temporary queues, depending on how you created them, you may need to remove the temporary queue after each request/response is done. Otherwise you will have loads of stagnant queues. If you are using `session.createTemporaryQueue` then the queue will be torn down when you do `session.close`.

**Comment by cmisztur** [comment]
+1 for Request/Response pattern.

**Comment by dizzzz** [comment]
@cmisztur Actually my idea was to have eXist-db as a passive component.... Like a webserver but then with JMS.
I'll study @adamretter 's input....
