### ISSUE TITLE
handleMessage( $content ) should not contain a document node

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/messaging-replication#15]
The current implementation returns a document-node() in stead of a 'normal' node.
This should be changed

**Comment by adamretter** [comment]
Why do you think it should not use a document node? If you look at many of eXist's modern extension functions which return XML or take XML they use document nodes and not elements. I believe this is because it is much more intuitive to the user when writing XPath across them, as users expect the same kinda behavior as fn:doc and fn:collection.

**Comment by dizzzz** [comment]
Thnx for you thoughts! 

The root of my idea is the following: Imagine a document <A><B>c</B></A>. if $content contains a document-node, the way to fetch the c-value is $content//A/B whilst $content/A/B looks more logical to me.

Or am I mistaken with my xpaths here?

**Comment by adamretter** [comment]
Well you do not need the `//` necessarily. If A is the first child of the document, then simply `$content/A` will work perfectly, which is much more logical than $content being the element `A`, as IMHO it fits with the behavior of other functions.

**Comment by dizzzz** [comment]
I am pretty use that $content/A does not work. I'll check.

**Comment by dizzzz** [comment]
you are right, it just works.

**Comment by adamretter** [comment]
That's XPath! ;-)
